<?php

use yii\db\Migration;

/**
 * Class m180318_134957_insert_route_data
 */
class m180318_134957_insert_route_data extends Migration
{
    public $routeData = "";
    const TABLE_NAME = 'auth_item';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->routeData = <<<DATA
[ {
	"name": "/*",
	"type": "2"
}, {
	"name": "/admin/*",
	"type": "2"
}, {
	"name": "/admin/assignment/*",
	"type": "2"
}, {
	"name": "/admin/assignment/assign",
	"type": "2"
}, {
	"name": "/admin/assignment/index",
	"type": "2"
}, {
	"name": "/admin/assignment/revoke",
	"type": "2"
}, {
	"name": "/admin/assignment/view",
	"type": "2"
}, {
	"name": "/admin/default/*",
	"type": "2"
}, {
	"name": "/admin/default/index",
	"type": "2"
}, {
	"name": "/admin/menu/*",
	"type": "2"
}, {
	"name": "/admin/menu/create",
	"type": "2"
}, {
	"name": "/admin/menu/delete",
	"type": "2"
}, {
	"name": "/admin/menu/index",
	"type": "2"
}, {
	"name": "/admin/menu/update",
	"type": "2"
}, {
	"name": "/admin/menu/view",
	"type": "2"
}, {
	"name": "/admin/permission/*",
	"type": "2"
}, {
	"name": "/admin/permission/assign",
	"type": "2"
}, {
	"name": "/admin/permission/create",
	"type": "2"
}, {
	"name": "/admin/permission/delete",
	"type": "2"
}, {
	"name": "/admin/permission/index",
	"type": "2"
}, {
	"name": "/admin/permission/remove",
	"type": "2"
}, {
	"name": "/admin/permission/update",
	"type": "2"
}, {
	"name": "/admin/permission/view",
	"type": "2"
}, {
	"name": "/admin/role/*",
	"type": "2"
}, {
	"name": "/admin/role/assign",
	"type": "2"
}, {
	"name": "/admin/role/create",
	"type": "2"
}, {
	"name": "/admin/role/delete",
	"type": "2"
}, {
	"name": "/admin/role/index",
	"type": "2"
}, {
	"name": "/admin/role/remove",
	"type": "2"
}, {
	"name": "/admin/role/update",
	"type": "2"
}, {
	"name": "/admin/role/view",
	"type": "2"
}, {
	"name": "/admin/route/*",
	"type": "2"
}, {
	"name": "/admin/route/assign",
	"type": "2"
}, {
	"name": "/admin/route/create",
	"type": "2"
}, {
	"name": "/admin/route/index",
	"type": "2"
}, {
	"name": "/admin/route/refresh",
	"type": "2"
}, {
	"name": "/admin/route/remove",
	"type": "2"
}, {
	"name": "/admin/rule/*",
	"type": "2"
}, {
	"name": "/admin/rule/create",
	"type": "2"
}, {
	"name": "/admin/rule/delete",
	"type": "2"
}, {
	"name": "/admin/rule/index",
	"type": "2"
}, {
	"name": "/admin/rule/update",
	"type": "2"
}, {
	"name": "/admin/rule/view",
	"type": "2"
}, {
	"name": "/admin/user/*",
	"type": "2"
}, {
	"name": "/admin/user/activate",
	"type": "2"
}, {
	"name": "/admin/user/change-password",
	"type": "2"
}, {
	"name": "/admin/user/delete",
	"type": "2"
}, {
	"name": "/admin/user/index",
	"type": "2"
}, {
	"name": "/admin/user/login",
	"type": "2"
}, {
	"name": "/admin/user/logout",
	"type": "2"
}, {
	"name": "/admin/user/request-password-reset",
	"type": "2"
}, {
	"name": "/admin/user/reset-password",
	"type": "2"
}, {
	"name": "/admin/user/signup",
	"type": "2"
}, {
	"name": "/admin/user/view",
	"type": "2"
}, {
	"name": "/content/*",
	"type": "2"
}, {
	"name": "/content/article/*",
	"type": "2"
}, {
	"name": "/content/article/create",
	"type": "2"
}, {
	"name": "/content/article/delete",
	"type": "2"
}, {
	"name": "/content/article/index",
	"type": "2"
}, {
	"name": "/content/article/update",
	"type": "2"
}, {
	"name": "/content/article/upload",
	"type": "2"
}, {
	"name": "/content/article/view",
	"type": "2"
}, {
	"name": "/content/subject/*",
	"type": "2"
}, {
	"name": "/content/subject/ajax-get-subjects",
	"type": "2"
}, {
	"name": "/content/subject/create",
	"type": "2"
}, {
	"name": "/content/subject/delete",
	"type": "2"
}, {
	"name": "/content/subject/index",
	"type": "2"
}, {
	"name": "/content/subject/update",
	"type": "2"
}, {
	"name": "/content/subject/upload",
	"type": "2"
}, {
	"name": "/content/subject/view",
	"type": "2"
}, {
	"name": "/content/tag/*",
	"type": "2"
}, {
	"name": "/content/tag/ajax-get-tags",
	"type": "2"
}, {
	"name": "/content/tag/create",
	"type": "2"
}, {
	"name": "/content/tag/delete",
	"type": "2"
}, {
	"name": "/content/tag/index",
	"type": "2"
}, {
	"name": "/content/tag/update",
	"type": "2"
}, {
	"name": "/content/tag/view",
	"type": "2"
}, {
	"name": "/debug/*",
	"type": "2"
}, {
	"name": "/debug/default/*",
	"type": "2"
}, {
	"name": "/debug/default/db-explain",
	"type": "2"
}, {
	"name": "/debug/default/download-mail",
	"type": "2"
}, {
	"name": "/debug/default/index",
	"type": "2"
}, {
	"name": "/debug/default/toolbar",
	"type": "2"
}, {
	"name": "/debug/default/view",
	"type": "2"
}, {
	"name": "/debug/user/*",
	"type": "2"
}, {
	"name": "/debug/user/reset-identity",
	"type": "2"
}, {
	"name": "/debug/user/set-identity",
	"type": "2"
}, {
	"name": "/gii/*",
	"type": "2"
}, {
	"name": "/gii/default/*",
	"type": "2"
}, {
	"name": "/gii/default/action",
	"type": "2"
}, {
	"name": "/gii/default/diff",
	"type": "2"
}, {
	"name": "/gii/default/index",
	"type": "2"
}, {
	"name": "/gii/default/preview",
	"type": "2"
}, {
	"name": "/gii/default/view",
	"type": "2"
}, {
	"name": "/member/*",
	"type": "2"
}, {
	"name": "/member/user/*",
	"type": "2"
}, {
	"name": "/member/user/delete",
	"type": "2"
}, {
	"name": "/member/user/index",
	"type": "2"
}, {
	"name": "/member/user/signup",
	"type": "2"
}, {
	"name": "/member/user/update",
	"type": "2"
}, {
	"name": "/member/user/view",
	"type": "2"
}, {
	"name": "/setting/*",
	"type": "2"
}, {
	"name": "/setting/log/*",
	"type": "2"
}, {
	"name": "/setting/log/clear",
	"type": "2"
}, {
	"name": "/setting/log/index",
	"type": "2"
}, {
	"name": "/setting/log/view",
	"type": "2"
}, {
	"name": "/setting/seo/*",
	"type": "2"
}, {
	"name": "/setting/seo/update",
	"type": "2"
}, {
	"name": "/site/*",
	"type": "2"
}, {
	"name": "/site/error",
	"type": "2"
}, {
	"name": "/site/index",
	"type": "2"
}, {
	"name": "/site/login",
	"type": "2"
}, {
	"name": "/site/logout",
	"type": "2"
}]
DATA;


    }


    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $data = \yii\helpers\Json::decode($this->routeData);
        for ($i=0; $i<count($data); ++$i){
            $this->insert(self::TABLE_NAME, $data[$i]);
        }
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        echo "m180318_134957_insert_route_data cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m180318_134957_insert_route_data cannot be reverted.\n";

        return false;
    }
    */
}
