<?php

use yii\db\Migration;

/**
 * Class m180318_134957_insert_route_data
 */
class m180318_122249_insert_route_data extends Migration
{
    public $routeData = "";
    const TABLE_NAME = 'auth_item';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        /*$this->routeData = <<<DATA
[ {
	"name": "/*",
	"type": "2"
}, {
	"name": "/admin/*",
	"type": "2"
}, {
	"name": "/admin/assignment/*",
	"type": "2"
}, {
	"name": "/admin/assignment/assign",
	"type": "2"
}, {
	"name": "/admin/assignment/index",
	"type": "2"
}, {
	"name": "/admin/assignment/revoke",
	"type": "2"
}, {
	"name": "/admin/assignment/view",
	"type": "2"
}, {
	"name": "/admin/default/*",
	"type": "2"
}, {
	"name": "/admin/default/index",
	"type": "2"
}, {
	"name": "/admin/menu/*",
	"type": "2"
}, {
	"name": "/admin/menu/create",
	"type": "2"
}, {
	"name": "/admin/menu/delete",
	"type": "2"
}, {
	"name": "/admin/menu/index",
	"type": "2"
}, {
	"name": "/admin/menu/update",
	"type": "2"
}, {
	"name": "/admin/menu/view",
	"type": "2"
}, {
	"name": "/admin/permission/*",
	"type": "2"
}, {
	"name": "/admin/permission/assign",
	"type": "2"
}, {
	"name": "/admin/permission/create",
	"type": "2"
}, {
	"name": "/admin/permission/delete",
	"type": "2"
}, {
	"name": "/admin/permission/index",
	"type": "2"
}, {
	"name": "/admin/permission/remove",
	"type": "2"
}, {
	"name": "/admin/permission/update",
	"type": "2"
}, {
	"name": "/admin/permission/view",
	"type": "2"
}, {
	"name": "/admin/role/*",
	"type": "2"
}, {
	"name": "/admin/role/assign",
	"type": "2"
}, {
	"name": "/admin/role/create",
	"type": "2"
}, {
	"name": "/admin/role/delete",
	"type": "2"
}, {
	"name": "/admin/role/index",
	"type": "2"
}, {
	"name": "/admin/role/remove",
	"type": "2"
}, {
	"name": "/admin/role/update",
	"type": "2"
}, {
	"name": "/admin/role/view",
	"type": "2"
}, {
	"name": "/admin/route/*",
	"type": "2"
}, {
	"name": "/admin/route/assign",
	"type": "2"
}, {
	"name": "/admin/route/create",
	"type": "2"
}, {
	"name": "/admin/route/index",
	"type": "2"
}, {
	"name": "/admin/route/refresh",
	"type": "2"
}, {
	"name": "/admin/route/remove",
	"type": "2"
}, {
	"name": "/admin/rule/*",
	"type": "2"
}, {
	"name": "/admin/rule/create",
	"type": "2"
}, {
	"name": "/admin/rule/delete",
	"type": "2"
}, {
	"name": "/admin/rule/index",
	"type": "2"
}, {
	"name": "/admin/rule/update",
	"type": "2"
}, {
	"name": "/admin/rule/view",
	"type": "2"
}, {
	"name": "/admin/user/*",
	"type": "2"
}, {
	"name": "/admin/user/activate",
	"type": "2"
}, {
	"name": "/admin/user/change-password",
	"type": "2"
}, {
	"name": "/admin/user/delete",
	"type": "2"
}, {
	"name": "/admin/user/index",
	"type": "2"
}, {
	"name": "/admin/user/login",
	"type": "2"
}, {
	"name": "/admin/user/logout",
	"type": "2"
}, {
	"name": "/admin/user/request-password-reset",
	"type": "2"
}, {
	"name": "/admin/user/reset-password",
	"type": "2"
}, {
	"name": "/admin/user/signup",
	"type": "2"
}, {
	"name": "/admin/user/view",
	"type": "2"
}, {
	"name": "/content/*",
	"type": "2"
}, {
	"name": "/content/article/*",
	"type": "2"
}, {
	"name": "/content/article/create",
	"type": "2"
}, {
	"name": "/content/article/delete",
	"type": "2"
}, {
	"name": "/content/article/index",
	"type": "2"
}, {
	"name": "/content/article/update",
	"type": "2"
}, {
	"name": "/content/article/upload",
	"type": "2"
}, {
	"name": "/content/article/view",
	"type": "2"
}, {
	"name": "/content/subject/*",
	"type": "2"
}, {
	"name": "/content/subject/ajax-get-subjects",
	"type": "2"
}, {
	"name": "/content/subject/create",
	"type": "2"
}, {
	"name": "/content/subject/delete",
	"type": "2"
}, {
	"name": "/content/subject/index",
	"type": "2"
}, {
	"name": "/content/subject/update",
	"type": "2"
}, {
	"name": "/content/subject/upload",
	"type": "2"
}, {
	"name": "/content/subject/view",
	"type": "2"
}, {
	"name": "/content/tag/*",
	"type": "2"
}, {
	"name": "/content/tag/ajax-get-tags",
	"type": "2"
}, {
	"name": "/content/tag/create",
	"type": "2"
}, {
	"name": "/content/tag/delete",
	"type": "2"
}, {
	"name": "/content/tag/index",
	"type": "2"
}, {
	"name": "/content/tag/update",
	"type": "2"
}, {
	"name": "/content/tag/view",
	"type": "2"
}, {
	"name": "/debug/*",
	"type": "2"
}, {
	"name": "/debug/default/*",
	"type": "2"
}, {
	"name": "/debug/default/db-explain",
	"type": "2"
}, {
	"name": "/debug/default/download-mail",
	"type": "2"
}, {
	"name": "/debug/default/index",
	"type": "2"
}, {
	"name": "/debug/default/toolbar",
	"type": "2"
}, {
	"name": "/debug/default/view",
	"type": "2"
}, {
	"name": "/debug/user/*",
	"type": "2"
}, {
	"name": "/debug/user/reset-identity",
	"type": "2"
}, {
	"name": "/debug/user/set-identity",
	"type": "2"
}, {
	"name": "/gii/*",
	"type": "2"
}, {
	"name": "/gii/default/*",
	"type": "2"
}, {
	"name": "/gii/default/action",
	"type": "2"
}, {
	"name": "/gii/default/diff",
	"type": "2"
}, {
	"name": "/gii/default/index",
	"type": "2"
}, {
	"name": "/gii/default/preview",
	"type": "2"
}, {
	"name": "/gii/default/view",
	"type": "2"
}, {
	"name": "/member/*",
	"type": "2"
}, {
	"name": "/member/user/*",
	"type": "2"
}, {
	"name": "/member/user/delete",
	"type": "2"
}, {
	"name": "/member/user/index",
	"type": "2"
}, {
	"name": "/member/user/signup",
	"type": "2"
}, {
	"name": "/member/user/update",
	"type": "2"
}, {
	"name": "/member/user/view",
	"type": "2"
}, {
	"name": "/setting/*",
	"type": "2"
}, {
	"name": "/setting/log/*",
	"type": "2"
}, {
	"name": "/setting/log/clear",
	"type": "2"
}, {
	"name": "/setting/log/index",
	"type": "2"
}, {
	"name": "/setting/log/view",
	"type": "2"
}, {
	"name": "/setting/seo/*",
	"type": "2"
}, {
	"name": "/setting/seo/update",
	"type": "2"
}, {
	"name": "/site/*",
	"type": "2"
}, {
	"name": "/site/error",
	"type": "2"
}, {
	"name": "/site/index",
	"type": "2"
}, {
	"name": "/site/login",
	"type": "2"
}, {
	"name": "/site/logout",
	"type": "2"
}]
DATA;*/
        $this->routeData = <<<ROUTE
[{
    "name": "/*",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/*",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/assignment/*",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/assignment/assign",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/assignment/index",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/assignment/revoke",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/assignment/view",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/default/*",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/default/index",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/menu/*",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/menu/create",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/menu/delete",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/menu/index",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/menu/update",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/menu/view",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/permission/*",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/permission/assign",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/permission/create",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/permission/delete",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/permission/index",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/permission/remove",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/permission/update",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/permission/view",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/role/*",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/role/assign",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/role/create",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/role/delete",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/role/index",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/role/remove",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/role/update",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/role/view",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/route/*",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/route/assign",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/route/create",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/route/index",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/route/refresh",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/route/remove",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/rule/*",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/rule/create",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/rule/delete",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/rule/index",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/rule/update",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/rule/view",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/user/*",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/user/activate",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/user/change-password",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/user/delete",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/user/index",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/user/login",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/user/logout",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/user/request-password-reset",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/user/reset-password",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/user/signup",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/admin/user/view",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/content/*",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/content/article/*",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/content/article/create",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/content/article/delete",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/content/article/index",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/content/article/update",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/content/article/upload",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/content/article/view",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/content/article/edit-upload",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/content/comment/*",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": "1522752877",
    "updated_at": "1522752877"
},
{
    "name": "/content/comment/delete",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": "1522752877",
    "updated_at": "1522752877"
},
{
    "name": "/content/comment/index",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": "1522752876",
    "updated_at": "1522752876"
},
{
    "name": "/content/comment/view",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": "1522753721",
    "updated_at": "1522753721"
},
{
    "name": "/content/reply/*",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": "1522753721",
    "updated_at": "1522753721"
},
{
    "name": "/content/reply/delete",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": "1522753721",
    "updated_at": "1522753721"
},
{
    "name": "/content/reply/index",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": "1522753721",
    "updated_at": "1522753721"
},
{
    "name": "/content/reply/view",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": "1522753721",
    "updated_at": "1522753721"
},
{
    "name": "/content/subject/*",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/content/subject/ajax-get-subjects",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/content/subject/create",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/content/subject/delete",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/content/subject/index",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/content/subject/update",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/content/subject/upload",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/content/subject/view",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/content/tag/*",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/content/tag/ajax-get-tags",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/content/tag/create",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/content/tag/delete",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/content/tag/index",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/content/tag/update",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/content/tag/view",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/debug/*",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/debug/default/*",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/debug/default/db-explain",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/debug/default/download-mail",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/debug/default/index",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/debug/default/toolbar",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/debug/default/view",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/debug/user/*",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/debug/user/reset-identity",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/debug/user/set-identity",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/gii/*",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/gii/default/*",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/gii/default/action",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/gii/default/diff",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/gii/default/index",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/gii/default/preview",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/gii/default/view",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/member/*",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/member/author/*",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": "1522661709",
    "updated_at": "1522661709"
},
{
    "name": "/member/author/sponsor",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": "1522661709",
    "updated_at": "1522661709"
},
{
    "name": "/member/author/upload",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": "1522661709",
    "updated_at": "1522661709"
},
{
    "name": "/member/user/*",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/member/user/delete",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/member/user/index",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/member/user/signup",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/member/user/update",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/member/user/view",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/setting/*",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/setting/friend/*",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": "1522332748",
    "updated_at": "1522332748"
},
{
    "name": "/setting/friend/create",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": "1522332748",
    "updated_at": "1522332748"
},
{
    "name": "/setting/friend/delete",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": "1522332748",
    "updated_at": "1522332748"
},
{
    "name": "/setting/friend/index",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": "1522332748",
    "updated_at": "1522332748"
},
{
    "name": "/setting/friend/update",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": "1522332748",
    "updated_at": "1522332748"
},
{
    "name": "/setting/friend/view",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": "1522332748",
    "updated_at": "1522332748"
},
{
    "name": "/setting/log/*",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/setting/log/clear",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/setting/log/index",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/setting/log/view",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/setting/seo/*",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/setting/seo/update",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/site/*",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/site/error",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/site/index",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/site/login",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
},
{
    "name": "/site/logout",
    "type": "2",
    "description": null,
    "rule_name": null,
    "data": null,
    "created_at": null,
    "updated_at": null
}]
ROUTE;



    }


    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $data = \yii\helpers\Json::decode($this->routeData);
        for ($i=0; $i<count($data); ++$i){
            $this->insert(self::TABLE_NAME, $data[$i]);
        }
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        echo "m180318_134957_insert_route_data cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m180318_134957_insert_route_data cannot be reverted.\n";

        return false;
    }
    */
}
